# Generated by Django 3.1.7 on 2021-03-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlc_app', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='muhammadxoja@gmail.coom', max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.CharField(default='kkuh', max_length=50),
        ),
    ]
